package com.yomeekoko.tredbase_payment_system.utils.enums;

public enum PermissionEnum {
    READ_ONE_PARENT,
    READ_ALL_PARENT,
    READ_ALL_PAYMENT,
    PROCESS_ALL_PAYMENT,
    CREATE_ONE_PARENT,
    UPDATE_ONE_PARENT,
    DELETE_ONE_PARENT,
    READ_ONE_STUDENT,
    READ_ALL_STUDENT,
    DISABLE_ONE_STUDENT,
    DELETE_ONE_STUDENT,
    CREATE_ONE_STUDENT,
    UPDATE_ONE_STUDENT,
    ADD_RATE,
    ADD_ADMINISTRATORS,


    READ_MY_PROFILE;
}
